version: '3'

services:
  sonarqube_db:
    image: mysql
    volumes:
      - ./sonardb_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASS}
      MYSQL_DATABASE: sonarqube
      MYSQL_USER: sonarqube
      MYSQL_PASSWORD: ${MYSQL_PASS}

  sonarqube:
    depends_on:
      - sonarqube_db
    image: sonarqube:latest
    restart: always
    ports:
      - "9000:9000"
      - "9092:9092"
    environment:
      SONARQUBE_JDBC_USERNAME: sonarqube
      SONARQUBE_JDBC_PASSWORD: ${MYSQL_PASS}
      SONARQUBE_JDBC_URL: jdbc:mysql://db:3306/sonarqube?useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true